### ISSUE TITLE
Request for PDF of “Enhancing Fault Localization in Industrial Software Systems via Contrastive Learning“

### ISSUE THREAD

**Issue by bupt01** [pppppkun/Falcon#1]
Hi,

I recently came across the abstract of this paper that really resonated with me, both in terms of its innovative approach and its practical implications. The paper seems to offer valuable insights that could significantly benefit my current research and applications I'm considering.

Unfortunately, I've been unable to find the PDF through Google or other online resources. If anyone here has access to this paper or knows where I could obtain a copy, I would greatly appreciate your assistance.

Thank you in advance for your help!

**Comment by lollipop190** [comment]
the link is here: https://pppppkun.github.io/files/icse25.pdf
